import 'dotenv/config'; 
import express from 'express';
import cors from 'cors';
import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';

import { v2 as cloudinary } from 'cloudinary';
import { CloudinaryStorage } from 'multer-storage-cloudinary'; //multer is a middleware for node.js
import multer from 'multer';





//secure connection pool to Neon
const connectionString = process.env.DATABASE_URL;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);

// 2. Give that connection directly to Prisma
const prisma = new PrismaClient({ adapter });
const app = express();






// Middleware
app.use(cors()); // Allows your React frontend to talk to this backend
app.use(express.json()); // Allows us to read JSON data from requests



// --- CLOUDINARY & MULTER SETUP ---
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET
});

const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: {
    folder: 'notes_workspace_attachments',
    allowed_formats: ['jpg', 'png', 'jpeg', 'gif', 'webp']
  } as any
});

const upload = multer({ storage: storage });







// --- ROUTES ---

// 1. Health Check (Just to test if the server is alive)
app.get('/', (req, res) => {
  res.send('Notes Workspace API is running securely');
});



// 2. GET all notes for a specific user
app.get('/api/notes', async (req, res) => {
  try {
    const { userId } = req.query;
    if (!userId) return res.status(400).json({ error: "userId is required" });

    const notes = await prisma.note.findMany({
      where: { userId: String(userId) },
      orderBy: { updatedAt: 'desc' } // Newest notes first
    });
    
    res.json(notes);
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch notes" });
  }
});



// 3. POST (Create) a new note
// POST (Create) a new note
app.post('/api/notes', async (req, res) => {
  try {
    const { id, title, content, userId, folderId } = req.body; 
    
    if (!userId) return res.status(400).json({ error: "userId is required" });

    // Check if the folder actually exists in the database first
    let validFolderId = null;
    if (folderId) {
      const folderExists = await prisma.folder.findUnique({ 
        where: { id: String(folderId) } 
      });
      if (folderExists) {
        validFolderId = String(folderId);
      }
    }

    const newNote = await prisma.note.create({
      data: {
        id: id,
        title: title || "Untitled Note",
        content: content || "",
        userId: userId,
        folderId: validFolderId 
      }
    });

    res.json(newNote);
  } catch (error) {
    console.error(" DATABASE ERROR:", error); 
    res.status(500).json({ error: "Failed to create note" });
  }
});




// 3.5 PUT (Update) an existing note
app.put('/api/notes/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const { title, content } = req.body;
    
    const updatedNote = await prisma.note.update({
      where: { id: String(id) },
      data: { title, content }
    });
    
    res.json(updatedNote);
  } catch (error) {
    res.status(500).json({ error: "Failed to update note" });
  }
});



// 4. DELETE a note
app.delete('/api/notes/:id', async (req, res) => {
  try {
    const { id } = req.params;
    await prisma.note.delete({
      where: { id: String(id) }
    });
    res.json({ message: "Note deleted successfully" });
  } catch (error) {
    res.status(500).json({ error: "Failed to delete note" });
  }
});


// --- FOLDER ROUTES ---

// GET all folders for a specific user
app.get('/api/folders', async (req, res) => {
  try {
    const { userId } = req.query;
    if (!userId) return res.status(400).json({ error: "userId is required" });

    const folders = await prisma.folder.findMany({
      where: { userId: String(userId) },
      orderBy: { createdAt: 'asc' } 
    });
    
    res.json(folders);
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch folders" });
  }
});




// POST (Create) a new folder
app.post('/api/folders', async (req, res) => {
  try {
    const { id, name, userId } = req.body; 
    if (!userId) return res.status(400).json({ error: "userId is required" });

    const newFolder = await prisma.folder.create({
      data: {
        id: id, // We use the ID generated by your React frontend so they match perfectly
        name: name || "New Folder",
        userId: userId
      }
    });

    res.json(newFolder);
  } catch (error) {
    console.error("FOLDER DATABASE ERROR:", error); 
    res.status(500).json({ error: "Failed to create folder" });
  }
});



// DELETE a folder
app.delete('/api/folders/:id', async (req, res) => {
  try {
    const { id } = req.params;
    await prisma.folder.delete({
      where: { id: String(id) }
    });
    res.json({ message: "Folder deleted successfully" });
  } catch (error) {
    console.error("🚨 FOLDER DELETE ERROR:", error);
    res.status(500).json({ error: "Failed to delete folder" });
  }
});



//for attachment
app.post('/api/upload',upload.single('file'),(req,res)=>{  //const upload = multer({ dest: 'uploads/' })
  try{
    if (!req.file){
      return res.status(400).json({error: "No file uploaded"});

    }
    console.log("Image successfully uploaded",req.file.path);
    res.json({url: req.file.path })

  }
  catch(error){
    console.error("Upload error");
    res.status(500).json({error: "Failed to upload image"});
  }
});
















// --- START SERVER ---
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`✅ Server is running on http://localhost:${PORT}`);
});